---
# tasks file for apache2

- name: Install Apache2 web server
  apt:
    name: apache2
    state: present
  

- name: Start and enable Apache2
  service:
    name: apache2
    state: started
    enabled: yes
  

- name: Enable HTTP service on the remote host
  ufw:
    rule: allow
    name: 'Apache Full'
  

- name: Reload UFW service after enabling HTTP service
  command: ufw reload
  

- name: Remove file from Apache2
  file:
    path: /var/www/html/index.html
    state: absent
