---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install MariaDB server
  apt:
    name: mariadb-server
    state: present

- name: Install MySQL Python library
  apt:
    name: python3-mysqldb
    state: present

- name: Start and enable MariaDB service
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Create WordPress database
  mysql_db:
    name: "{{ wordpress_db }}"
    state: present

- name: Create WordPress user with privileges
  mysql_user:
    name: "{{ wordpress_dbuser }}"
    password: "{{ wordpress_dbpass }}"
    priv: "{{ wordpress_db }}.*:ALL"
    state: present

